version: '3.3'
services:
  nginx:
    build: ./nginx
    image: pstyp94/petginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - back-end 
    - front-end

  mysql:
    build: ./mysql
    image: pstyp94/pet-db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
      

  back-end:
    build: ./back-end
    image: pstyp94/backend
    ports:
    - target: 9966
      published: 9966
      protocol: tcp


  front-end:
    build: ./front-end
    image: pstyp94/frontend
    ports:
    - target: 4200
      published: 4200
      protocol: tcp
    depends_on:
    - back-end 

