apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic 
  template:
    metadata:
      name: petclinic
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: pstyp94/backend
        ports:
          - containerPort: 9966

---

apiVersion: v1
kind: Service
metadata:
   name: petclinic
   labels:
     app: petclinic      
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 9966
       targetPort: 9966
   selector:
     app: petclinic
