apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pstyp94/frontend
        ports:
          - containerPort: 4200

---

apiVersion: v1
kind: Service
metadata:
   name: frontend
   labels:
     app: frontend      
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 4200
       targetPort: 4200
   selector:
     app: frontend