apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-petclinic
  labels:
    app: mysql-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-petclinic 
  template:
    metadata:
      name: mysql-petclinic
      labels:
        app: mysql-petclinic
    spec:
      containers:
      - name: mysql-petclinic
        image: pstyp94/pet-db
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                      secretKeyRef:
                              name: dbpass
                              key: dbpass
        ports:
          - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
   name: mysql-petclinic
   labels:
     app: mysql-petclinic
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 3306
       targetPort: 3306
   selector:
     app: mysql-petclinic
